game: connect4
algorithm:
  name: mcgs
  core:
    num_sims: 1000
    c_exploration: 1.414
    max_rollout_depth: null
    max_nodes: 100000
    batch_size: 1
  trainer:
    num_test_games: 10
    device: cpu
    random_seed: 42
    verbose: true

checkpoint:
  custom_folder_name: "mcgs_bob"
